name: Run CI
on: push
jobs:
  build-and-test:
   runs-on: ubuntu-latest
   steps:
   - name: Check out repository code
     uses: actions/checkout@v3
   - name: Login to Docker Hub
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.ranjithreddy321 }}
       password: ${{ secrets.ranjith@52015 }}

        
